apps/account/models.py
from apps.ext import db
from flask_login import UserMixin
from passlib.apps import custom_app_context

"""
如果使用当前user对象作为登录模块的模型
必须提供
is_active
is_authenticated
is_anonymous
"""


class User(db.Model, UserMixin):
    uid = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(64), unique=True, index=True, nullable=False)
    phone = db.Column(db.String(32), unique=True, nullable=False)
    email = db.Column(db.String(64), unique=True)
    _password = db.Column(db.String(128), nullable=False)
    _is_active = db.Column(db.Boolean, default=False)
    is_delete = db.Column(db.Boolean, default=False)

    @property
    def is_active(self):
        return self._is_active

    def get_id(self):
        return self.uid

    @property
    def password(self):
        return self._password

    # 设置密码  对密码进行加密
    @password.setter
    def password(self, password):
        if password:
            self._password = custom_app_context.encrypt(password)
        else:
            raise Exception('密码为空!!!!')

    # 验证密码
    def verify_password(self, password):
        return custom_app_context.verify(password, self._password)

apps/__init__.py
from flask import Flask
from apps.account.views import account
from apps.ext import init_ext


def create_app():
    app = Flask(__name__)
    app.debug = True
    app.config['SECRET_KEY'] = 'sadasdasd1213231123'
    init_ext(app)
    register_bp(app)
    return app


def register_bp(app):
    app.register_blueprint(account)

apps/account/views.py
from operator import or_

from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, logout_user, login_user

from apps.account.models import User
from apps.ext import db, lm

account = Blueprint('account', __name__, template_folder='templates')


# 插件必须要实现的方法 session获取用户的对象
@lm.user_loader
def load_user(uid):
    return User.query.get(uid)


@account.route('/login/', methods=['get', 'post'])
def login():
    if request.method == 'GET':
        return render_template('account.html')
    elif request.method == 'POST':
        username = request.values.get('username')
        password = request.values.get('password')
        users = User.query.filter(User.username == username)
        if users:
            if users.first() and users.first().is_active:
                user = users.first()
                if user.verify_password(password):
                    login_user(user, remember=True)
                    return render_template('index.html', msg='登录成功!!!')
                else:
                    return render_template('account.html', msg='账号或者密码有误,请重新输入!!!!')
            else:
                return render_template('account.html', msg='账号未激活,请激活后再登录!!!')
        else:
            return render_template('account.html', msg='用户不存在,请先注册在登录!!!')


@account.route('/register/', methods=['get', 'post'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        username = request.values.get('username')
        password = request.values.get('password')
        phone = request.values.get('phone')
        email = request.values.get('email')
        if username and password and phone:
            user = User.query.filter(or_(User.username == username, User.phone == phone)).first()
            if user:
                return render_template('register.html', msg='该用户名或者电话号码已经注册过了!!!')
            else:
                user = User(username=username, password=password, phone=phone, email=email, _is_active=0)
                db.session.add(user)
                db.session.commit()
                return render_template('index.html', msg='注册成功!!!')
        else:
            return render_template('register.html', msg='注册失败,请核对您的输入!!!!')


@account.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect('/')


@account.route('/')
def index():
    return render_template('index.html')

apps/account/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
         body{
            background: url('/apps/static/img/snow.jpg');
        }
        .head_div{
            margin: 10% 30%;
            {#border: 1px solid cornflowerblue;#}
            background: cornflowerblue;
        }
        .head_div>p{
            font-size: 30px;
            text-align: center;
            padding-top: 10px;
        }
         .input_div{
            margin-bottom: 25px;
        }
        .input_div>label{
            display: block;
            font-size: 20px;
            {#height: 40px;#}
            margin-bottom: 10px;
            padding-bottom: 5px;
            margin-left: 10px;
        }
        .input_div>input{
            width: 99%;
            height: 40px;
            background: none;
            border: 1px solid black;
        }
       .input_a{
           display: block;
           width: 99%;
           height: 40px;
           background: none;
           border: 1px solid black;
           {#font-size: 20px;#}
           text-align: center;
           margin-top: 25px;
       }
    </style>
</head>
<body>
{% if msg %}
    {{ msg }}
{% endif %}
<div class="head_div">
    <p>登录</p>
    <form action="{{ url_for('account.login') }}" method="post">
        <div class="input_div">
            <label for="">用户名:</label>
            <input type="text" name="username">
        </div>
        <div class="input_div">
            <label for="">密码:</label>
            <input type="password" name="password">
        </div>
        <div class="input_div">
            <input type="submit" value="登录">
            <a href="{{ url_for('account.register') }}" class="input_a">注册</a>
        </div>
    </form>
</div>

</body>
</html>

apps/account/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}

    {% endblock %}
    {% block jq %}

    {% endblock %}
</head>
<body>
{% block head %}

{% endblock %}
{% block main %}

{% endblock %}
{% block title %}

{% endblock %}
</body>
</html>

apps/account/templates/index.html
{% extends 'base/base.html' %}
{% block head %}
    {% include 'top.html' %}
{% endblock %}
{% block main %}
    <p>欢迎来到91pro</p>
{% endblock %}

apps/account/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        body{
            background: url('/apps/static/img/snow.jpg');
        }
        .head_div{
            margin: 10% 30%;
            {#border: 1px solid cornflowerblue;#}
            background: cornflowerblue;
        }
        .head_div>p{
            font-size: 30px;
            text-align: center;
            padding-top: 10px;
        }
         .input_div{
            margin-bottom: 25px;
        }
        .input_div>label{
            display: block;
            font-size: 20px;
            {#height: 40px;#}
            margin-bottom: 10px;
            padding-bottom: 5px;
            margin-left: 10px;
        }
        .input_div>input{
            width: 99%;
            height: 40px;
            background: none;
            border: 1px solid black;
        }
       .input_a{
           display: block;
           width: 99%;
           height: 40px;
           background: none;
           border: 1px solid black;
           {#font-size: 20px;#}
           text-align: center;
           margin-top: 25px;
       }
    </style>
</head>
<body>
{% if msg %}
    {{ msg }}
{% endif %}
<div class="head_div">
    <p>注册</p>
    <form action="{{ url_for('account.register') }}" method="post">
    <div class="input_div">
        <label for="">用户名:</label>
        <input type="text" name="username" placeholder="请输入您的用户名" required>
    </div>
    <div class="input_div">
        <label for="">邮箱:</label>
        <input type="email" name="email" placeholder="请输入您的邮箱" required>
    </div>
    <div class="input_div">
        <label for="">手机号:</label>
        <input type="number" name="phone" pattern="^(13\d|14[5|7]|15\d|166|17[3|6|7]|18\d)\d{8}$" placeholder="请输入您的手机号" required>
    </div>
    <div class="input_div">
        <label for="">密码:</label>
        <input type="password" name="password" placeholder="请输入密码" data-error="密码最小长度为6位" required>
    </div>
    <div class="input_div">
        <label for="">确认密码:</label>
        <input type="password" name="confirm_password" placeholder="请再次输入密码" data-error="两次输入不一致" required>
    </div>
    <div class="input_div">
        <input type="submit" value="注册">
        <a href="{{ url_for('account.login') }}" class="input_a">返回</a>
    </div>
</form>
</div>
</body>
</html>

apps/account/templates/top.html
{% if current_user.is_authenticated %}
    <span>{{ current_user.username }}</span>
    <a href="{{ url_for('account.logout') }}">退出</a>
{% else %}
    <a href="{{ url_for('account.login') }}">登录</a>
    <a href="{{ url_for('account.register') }}">注册</a>
{% endif %}